In [2]:
import numpy as np

In [3]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [4]:
b[0, :]

array([1., 2., 3.])

In [5]:
b[:,0]

array([1., 3.])

In [6]:
# create 2 by 7 array
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
# [startindex : endindex: stepsize]
c[0, 1:-1:2]

array([2, 4, 6])

In [7]:
a = c

In [11]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [12]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [13]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [14]:
a[:,2] = [11,22]
a

array([[ 1,  2, 11,  4,  5,  6,  7],
       [ 8,  9, 22, 11, 12, 20, 14]])

In [15]:
c

array([[ 1,  2, 11,  4,  5,  6,  7],
       [ 8,  9, 22, 11, 12, 20, 14]])

In [16]:
# for 3D array / work outside in 
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
a

array([[ 1,  2, 11,  4,  5,  6,  7],
       [ 8,  9, 22, 11, 12, 20, 14]])

In [18]:
c[0, 0, 1]

np.int64(2)

In [19]:
c[0,1,1]

np.int64(4)

In [20]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [21]:
a[:, 2] = 20

In [22]:
a

array([[ 1,  2, 20,  4,  5],
       [ 6,  7, 20,  9, 10]])