In [3]:
import numpy
import pandas as pd

In [4]:
a = numpy.array([1, 2, 3, 4, 5, 6])

In [5]:
a[:-2]

array([1, 2, 3, 4])

In [6]:
a[:2]

array([1, 2])

In [7]:
for x in a[:-2]:
    print(x)

1
2
3
4


In [8]:
a.dtype

dtype('int64')

In [9]:
a = numpy.arange(5)

In [10]:
a

array([0, 1, 2, 3, 4])

In [11]:
a + 20

array([20, 21, 22, 23, 24])

In [4]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])

In [5]:
ambassadors

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object